### ISSUE TITLE
Inclusion into Jupyter Notebooks

### ISSUE THREAD

**Issue by cap-jmk** [EBjerrum/rdeditor#3]
Hey, 

Thank you for your repo on the rdeditor. It is really cool. Do you have any idea on how to include that into Jupyter notebooks?

**Comment by EBjerrum** [comment]
Yes, I've been working on it, but it's only halfway done and is buggy, and I don't currently have time to finish it.

**Comment by cap-jmk** [comment]
Okay, no problem. Maybe we could open a branch?

**Comment by EBjerrum** [comment]
Yes, good idea, I'll try and find the time to make a branch from the sandbox code

**Comment by cap-jmk** [comment]
Cool, thanks :)

**Comment by EBjerrum** [comment]
Pushed a branch jupyter_integration with the prototype code.
After installation it should be possible to:

from rdeditor.jupyter_widget import EditMol
app  = EditMol()

It lives independent from the other code, which it really shouldn't.

**Comment by apahl** [comment]
Hi, I just tried out the rdEditor and agree that it is awesome. Great work, Esben.
Regarding the request mentioned here, I would just like to humbly point out, that there is the possibility to integrate Peter Ertl's Javascript Molecule Editor (JSME) into a Python Jupyter notebook:
[Github link](https://github.com/apahl/rdkit_ipynb_tools/blob/c259ac8ee75709becd2a5e67f9a913bd20e0ae38/rdkit_ipynb_tools/tools.py#L2514)  
[Tutorial at RDKit UGM 2016](https://github.com/rdkit/UGM_2016/blob/master/Notebooks/Pahl_NotebookTools_Tutorial.ipynb) (cell 17)
(Disclaimer: I have not used the code in quite some time and have moved from mol lists to dataframes, but it should be possible to take the `jsme()` function out of that module.)
KR Axel

**Comment by EBjerrum** [comment]
Strange, I got mail that Axel added a comment, but I can't see it on GitHub????
Esben Jannik Bjerrum
cand.pharm, Ph.D
Phone +46 76 303 90 13 
http://dk.linkedin.com/in/esbenbjerrum
https://www.cheminformania.com

 

    On Monday, March 3, 2025 at 10:07:56 AM GMT+1, Axel Pahl ***@***.***> wrote:  
 
  
Hi, I just tried out the rdEditor and agree that it is awesome. Great work, Esben.
Regarding the request mentioned here, I would just like to humbly point out, that there is the possibility to integrate Peter Ertl's Javascript Molecule Editor (JSME) into a Python Jupyter notebook:
Github link
Tutorial at RDKit UGM 2016 (cell 17)
(Disclaimer: I have not used the code in quite some time and have moved from mol lists to dataframes, but it should be possible to take the jsme() function out of that module.)
KR Axel

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
apahl left a comment (EBjerrum/rdeditor#3)
Hi, I just tried out the rdEditor and agree that it is awesome. Great work, Esben.
Regarding the request mentioned here, I would just like to humbly point out, that there is the possibility to integrate Peter Ertl's Javascript Molecule Editor (JSME) into a Python Jupyter notebook:
Github link
Tutorial at RDKit UGM 2016 (cell 17)
(Disclaimer: I have not used the code in quite some time and have moved from mol lists to dataframes, but it should be possible to take the jsme() function out of that module.)
KR Axel

**Comment by apahl** [comment]
Yes, sorry for the confusion, Esben, I deleted my comment again. I did not read this issue thread to the end, and originally wanted to point out that there is the possibility to use the JSME in Jupyter Notebooks. But you solved it with the rdEditor, so no need to use the JSME.  
Awesome work with this project, really.
KR Axel

**Comment by EBjerrum** [comment]
Ah ok. But no. The jupyter branch is seriously not working great. It would need more developer time to be usable, but I havent looked at it for ages.

Yahoo Mail: Search, organise, conquer 
 
  On Mon, 3 Mar 2025 at 20:09, Axel ***@***.***> wrote:    
Yes, sorry for the confusion, Esben, I deleted my comment again. I did not read this issue thread to the end, and originally wanted to point out that there is the possibility to use the JSME in Jupyter Notebooks. But you solved it with the rdEditor, so no need to use the JSME.
Awesome work with this project, really.
KR Axel

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>
apahl left a comment (EBjerrum/rdeditor#3)
Yes, sorry for the confusion, Esben, I deleted my comment again. I did not read this issue thread to the end, and originally wanted to point out that there is the possibility to use the JSME in Jupyter Notebooks. But you solved it with the rdEditor, so no need to use the JSME.
Awesome work with this project, really.
KR Axel
